name: bot_web
version: 0.20.3
author: Kevin Moore <kevin@thinkpixellab.com>
description: A collection of (mostly) general libraries to make working with Dart more productive.
homepage: https://github.com/kevmoo/bot_web.dart
documentation: http://kevmoo.github.io/bot_web.dart/
environment:
  sdk: '>=0.6.5'
dependencies:
  bot: '>=0.22.1'
  logging: '>=0.6.5'
  meta: '>=0.6.5'
dev_dependencies:
  browser: '>=0.6.5'
  hop: '>=0.23.0'
  html5lib: '>=0.4.3'
  unittest: '>=0.6.5'
