name: bot_web
version: 0.20.5-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: A collection of (mostly) general libraries to make working with Dart more productive.
homepage: https://github.com/kevmoo/bot_web.dart
documentation: http://kevmoo.github.io/bot_web.dart/
environment:
  sdk: '>=0.6.9'
dependencies:
  bot: '>=0.23.0'
  logging: '>=0.6.9'
  meta: '>=0.6.9'
dev_dependencies:
  bot_test: '>=0.1.0'
  browser: '>=0.6.9'
  hop: '>=0.24.1+1'
  html5lib: '>=0.4.4'
  path: '>=0.6.9'
  unittest: '>=0.6.9'
